### ISSUE TITLE
Should depend on seaborn-base not seaborn

### ISSUE THREAD

**Issue by jamesmyatt** [conda-forge/xarray-feedstock#117]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

The dependency on seaborn should be seaborn-base (like matplotlib-base).

I can make a PR + repo-patch when I get time.

### Installed packages

N/A

### Environment info

N/A

**Comment by jamesmyatt** [comment]
Actually it's just a constraint, but still

**Comment by kmuehlbauer** [comment]
@jamesmyatt Thanks for setting up the solutions. Would you mind notifying here when everything is in play?

**Comment by jamesmyatt** [comment]
recipe has been updated. repodata patch is ready for review.

**Comment by jamesmyatt** [comment]
Patches have been merged :+1:
