### ISSUE TITLE
Python 3.4 support

### ISSUE THREAD

**Issue by gbrener** [conda-forge/xarray-feedstock#24]
Hey @ocefpaf , thanks for your work on this feedstock. I noticed you removed Python 3.4 support here: https://github.com/conda-forge/xarray-feedstock/commit/7dfd7a70e5ce9f17b3964a9b2752e321031d9cc6 even though xarray appears to have support for Python 3.4 . Was there a reason for doing this?

**Comment by ocefpaf** [comment]
We removed Python 3.4 from all of `conda-forge` because we are CI limited. We chose to support only Python 2.7, 3.5, and 3.6. Sorry...

**Comment by gbrener** [comment]
Ok, thanks for the fast response.
