### ISSUE TITLE
This should probably depend on dask-core, not dask

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/xarray-feedstock#36]

**Comment by SylvainCorlay** [comment]
We came across this with @jasongrout and @martinRenou.

Would it be an issue if `xarray` did not depend on `dask` at all?

**Comment by SylvainCorlay** [comment]
The same question holds with NetCDF etc...

**Comment by SylvainCorlay** [comment]
If you want to constrain the version of dask that may be used, without making it a dependency, you can use the  `run_constrained:` statement in the recipe.

**Comment by jhamman** [comment]
There was some consideration of dropping optional dependencies in #5. We opted against it at the time but I think it would be worth revisiting. Perhaps even developing an xarray-core feedstock.

**Comment by jhamman** [comment]
closed via #37
