### ISSUE TITLE
new xarray 2022.10.0 has landed, will this magically appear on conda-forge?

### ISSUE THREAD

**Issue by durack1** [conda-forge/xarray-feedstock#78]
### Comment:

`xarray` [2022.10.0 was released 3 hrs ago](https://github.com/pydata/xarray/releases/tag/v2022.10.0), will this magically appear on [conda-forge](https://anaconda.org/conda-forge/xarray), or is some intervention (this issue) required to start the process?

**Comment by ocefpaf** [comment]
Yep. See #79 (The bot runs every hour so if it takes more than 2/3 ish  hours we may need to check if something went wrong. Anything less than that is OK.)
